name: impaktfull_cms_example
description: "Demonstrates how to use the impaktfull_cms plugin."
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  impaktfull_cms:
    path: ../
  impaktfull_ui: ">=0.49.0 <1.0.0"

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
